

export const REQUEST_API_DATA = 'REQUEST_API_DATA'
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA'
export const REQUEST_HELLO_WORLD = 'REQUEST_HELLO_WORLD'
export const RECEIVE_HELLO_WORLD = 'RECEIVE_HELLO_WORLD'


export const SUBMIT_FORM = 'SUBMIT_FORM'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_FIELD_ERROR = 'SUBMIT_FORM_FIELD_ERROR'

export const SUBMIT_FORM_ERROR = 'SUBMIT_FORM_ERROR'